# Generated by Django 4.2.28 on 2026-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
